### ISSUE TITLE
what configuration should i use if i want to upload on every 200kb or 1 minute, but never upload to the same file name twice, eg: avoid Versioning

### ISSUE THREAD

**Issue by yosiweinreb** [Coggle/s3-streamlogger#11]

**Comment by autopulated** [comment]
You can achieve that by setting the `rotate_every` option to 0, and the `buffer_size` and `upload_every` options to 200000 (bytes) and 60000 (milliseconds) respectively.

If `rotate_every` is 0 then every time the file is uploaded a new name will be used. Beware that as the file name used only changes once per second if more than 200kb of data is written in one second then data may be overwritten.

It might be safer to set `rotate_every` to 1000 (i.e. 1 second), and store data in a bucket with versioning disabled, if that's an option for you.

**Comment by yosiweinreb** [comment]
hi, thanks.
what i did eventually is set the flag `forceNewFile` inside the module to
true.
also i configured the filename to work in milisecs resolution, to avoid the
issue of 200kb > 1sec,
