### ISSUE TITLE
How to pipe streamlogger to stdout

### ISSUE THREAD

**Issue by loretoparisi** [Coggle/s3-streamlogger#19]
I'm running within node some processes that outputs to `stdout`. So I do a pipe to these `child_process` and get the output in node. Would be possibile to pipe the s3-streamlogger` to stdout i.e. something like:

```
var access = require('fs').createWriteStream('./var/log/api.log');
process.stdout.write = process.stderr.write = access.write.bind(access);
```

**Comment by autopulated** [comment]
Thanks for your question – I don't understand the issue you're having though. s3-streamlogger writes all its output to stdout, so you should be able to pipe this wherever you want.

Can you explain further?

**Comment by autopulated** [comment]
s3-streamlogger is a writable stream, it doesn't emit any output that you can pipe elsewhere. You could use a module like [tee](https://www.npmjs.com/package/tee) to pipe a single readable stream into both s3-streamlogger and also to stdout though?

**Comment by loretoparisi** [comment]
@autopulated sorry I did not express myself in the right way. I have an application that by defaults (and I cannot change it) pipes to `stdout`. As soon as I can override this behavior and pipe some where else like showed above, how could get that stream and pass to `s3-streamlogger` in order to send those application's logs to s3?

**Comment by autopulated** [comment]
Ah OK I understand, 

If you are running your app from within node, you could pipe the stdout stream into a s3-streamlogger stream like this:

```js
var spawn = require('child_process').spawn;
var S3StreamLogger = require('s3-streamlogger').S3StreamLogger;

var s3Stream = new S3StreamLogger({ ... });
var myAppProcess = spawn('some-application', ['--args'], { stdio: ['pipe'] });

myAppProcess.stdout.pipe(s3Stream);
```

**Comment by loretoparisi** [comment]
Thanks a lot, that is it!
