### ISSUE TITLE
S3 Logger clears buffer before uploading data when rotating files.

### ISSUE THREAD

**Issue by AsakerMohd** [Coggle/s3-streamlogger#25]
I'm using this package for one of our features. It works flawlessly except when it has to rotate files. We are receiving regular logs, a couple each second. So as you might guess, our log file grows very fast. I found out that each time a rotation has to occur, the logs that caused the buffer to grow to the max file limit never get logged. 

After extensively reading through the index file for the module, It turns out that that the _upload function calls the _newFile function which clears the buffer before uploading, thus, causing any data that causes the rotation due to file size (not time) to be lost. And after reading the comment above the _newfile function, it looks like the intended use is when there is "no un-uploaded data" or else any un-uploaded data would be lost.

 I think a good solution is to use Mutex locks or any synchronization mechanism to prevent addition to the buffer while a new file is being created and to create the new file after uploading the data that caused the buffer to grow to max_size.

**Comment by autopulated** [comment]
I think #26 should resolve this - could you test?
