### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by tuananhcwrs** [Coggle/s3-streamlogger#27]
Hello,

With just:

npm install --save winston
npm install --save s3-streamlogger

==>
will have these in package.json file:

"dependencies": {
    "s3-streamlogger": "^1.5.0",
    "winston": "^3.2.1"
  }

and write this code in index.js

`var winston        = require('winston');
var S3StreamLogger = require('s3-streamlogger').S3StreamLogger;
 
var s3_stream = new S3StreamLogger({
             bucket: "mys3bucket",
      access_key_id: "...",
  secret_access_key: "..."
});
 
var transport = new winston.transports.File({
  stream: s3_stream
});
// see error handling section below
transport.on('error', function(err){/* ... */});
 
var logger = new (winston.Logger)({
  transports: [file_transport]
});
 
 
logger.info('Hello Winston!');`

It fires

throw new ERR_INVALID_ARG_TYPE('path', 'string', path);

when run: node index

Could you please take a look?
Regards.

**Comment by tuananhcwrs** [comment]
Seems the reason because if the latest winston.

**Comment by JakeCube** [comment]
Hi is there any solution for this??

**Comment by autopulated** [comment]
@JakeCube I believe the solution is the updated docs here: https://github.com/Coggle/s3-streamlogger/pull/28/files
