### ISSUE TITLE
Suggestion to add option for content type

### ISSUE THREAD

**Issue by pwages** [Coggle/s3-streamlogger#30]
I noticed the uncompressed files uploaded to my S3 bucket all had a content type of "application/octet-stream". Would it be possible to add this a configurable option or infer it based on compressed vs. plaint text? 
With this being set to "text/plain" or configurable to "text/plain", I could view the file directly in S3 vs. having it trigger a download.

**Comment by autopulated** [comment]
PRs welcome :)

Probably just set the `ContentType` option for the `putObject` call here: https://github.com/Coggle/s3-streamlogger/blob/master/index.js#L124 based on whether this.compress is true or not.

**Comment by pwages** [comment]
Yes, I can do that! Opened here: https://github.com/Coggle/s3-streamlogger/pull/31
