### ISSUE TITLE
Allow modification of the parameters passed to `s3.putObject()`

### ISSUE THREAD

**Issue by georgevarghese185** [Coggle/s3-streamlogger#32]
I have a use case where I need log files to be uploaded to S3 with a custom `Expires` value. It could be added as another optional parameter like how `tags` and `acl` were added. But then I thought about how everyone might have different requirements to pass more custom parameters to `s3.putObject()` like Metadata, StorageClass etc..

Could there be a way for someone to easily modify the final `param` object that's being passed into `s3.putObject()`? Either by extending the class and overriding some private method or by taking a pre-populated `param` object in the constructor and using that as a base object for `putObject()`. That way, each `putObject` parameter doesn't have to be added one by one as separate optional parameters to the `S3StreamLogger` constructor.

Do you have any thoughts on whether this makes sense and how it could be implemented? I can take it up if needed

**Comment by autopulated** [comment]
PR welcome adding a `param` option to the options field, but if you want to specify a custom Expires value on each upload (e.g. X days in the future), possibly something more flexible than that is needed? Maybe it would make sense to allow overriding of the `putObject` function used instead?

**Comment by georgevarghese185** [comment]
Yes, overriding sounds like a much better idea. Specifically [this section](https://github.com/Coggle/s3-streamlogger/blob/0cfca1f384f14cf9dc7d1ed2758044213f151494/index.js#L144) which calls `s3.putObject()`. I'm thinking of moving this part from inside `S3StreamLogger#_upload()` to a separate, overridable method like `S3StreamLogger#putObject(params, callback)`. Then any user could override that and modify the S3 Put Object payload.

I'll create a PR when I get some time
