### ISSUE TITLE
Stream logger left hanging even after `stream.end()` is called

### ISSUE THREAD

**Issue by georgevarghese185** [Coggle/s3-streamlogger#34]
When calling `stream.end()` on an `S3StreamLogger` object, the stream doesn't immediately flush the buffer and upload the log data to S3. Instead, it waits until the next `upload_every` interval before it actually ends.

The very last thing my code was doing was calling `stream.end()` and I noticed the node process was left hanging for a good 20 seconds (default `options.upload_every` value) before the log file was finally uploaded to S3 and the process ended.

I think this should be an easy fix. You just have to add a [_final method](https://nodejs.org/api/stream.html#stream_writable_final_callback) to the stream class that calls `this._upload()` inside it.

Let me know if this approach sounds fine and I can create a PR if needed

**Comment by autopulated** [comment]
👍 That sounds good, PR welcome!

**Comment by autopulated** [comment]
Published 1.6.1 including #37
