### ISSUE TITLE
typo in repo description

### ISSUE THREAD

**Issue by imgntn** [Coggle/s3-streamlogger#36]
just missing an 'n' from winston here: 

Node.js stream for logging to s3 with rotated object names. Usable as a wiston-file stream.

**Comment by autopulated** [comment]
PR welcome!

**Comment by imgntn** [comment]
i can't, it's in the github description at the top of the repo... it's not part of the actual code :)

**Comment by autopulated** [comment]
Oh sorry 😆 fixed now!
