### ISSUE TITLE
Add in AWS S3 Storage Class option

### ISSUE THREAD

**Issue by todurnatesh** [Coggle/s3-streamlogger#38]
https://github.com/Coggle/s3-streamlogger/blob/aef06b88346a8563dfef816dc823338d6e0b644f/index.js#L83

It is better to add in AWS storage class option while using s3.putObject to upload file object
We can use StorageClass  parameter option to do the same. 

I can raise a PR for the same provided I have access rights

**Comment by autopulated** [comment]
Fixed by #39
