### ISSUE TITLE
Move to AWS SDK v3

### ISSUE THREAD

**Issue by gkentr** [Coggle/s3-streamlogger#43]
This would be mostly to eliminate warnings at startup:

```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

Looks like modifying the SDK import either by hand or running: 

```shell
npx aws-sdk-js-codemod -t v2-to-v3 index.js
```

should do it.

**Comment by autopulated** [comment]
PRs welcome 👍 

We no longer use this at Coggle (we just use cloudwatch logs now), but happy to publish a version supporting this if it's still useful to people.

**Comment by autopulated** [comment]
Updated to AWS SDK v3 in `1.9.0`.
